import { colors } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  backFab: {
    position: "absolute",
    left: 16,
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },
  recenterFab: {
    position: "absolute",
    right: 16,
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 8,
  },
  recenterFabActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  iconButton: {
    width: 42,
    height: 42,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  modeSwitch: {
    position: "absolute",
    left: 16,
    right: 16,
    flexDirection: "row",
    gap: 8,
    padding: 4,
    borderRadius: 18,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  modeButton: {
    flex: 1,
    height: 42,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  modeButtonSelected: {
    backgroundColor: colors.primary,
  },
  modeText: {
    fontSize: 12,
    fontWeight: "800",
    color: colors.primary,
  },
  modeTextSelected: {
    color: colors.textOnPrimary,
  },
  panel: {
    position: "absolute",
    left: 14,
    right: 14,
    bottom: 14,
    gap: 12,
  },
  panelHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  panelTitleBlock: {
    flex: 1,
  },
  panelTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: colors.text,
  },
  panelHint: {
    marginTop: 2,
    fontSize: 12,
    color: colors.textStrong,
  },
  pinBadge: {
    width: 36,
    height: 36,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FEE2E2",
  },
  mapMarker: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.surface,
    shadowColor: "#000000",
    shadowOpacity: 0.2,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  newMapMarker: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.danger,
  },
  quartierMapMarker: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.surface,
    backgroundColor: "#F97316",
    elevation: 4,
  },
  quartierMapMarkerActive: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.danger,
  },
  quartierMapMarkerText: {
    color: colors.textOnPrimary,
    fontSize: 12,
    fontWeight: "900",
  },
  pinList: {
    gap: 8,
  },
  pinChip: {
    minWidth: 48,
    height: 34,
    borderRadius: 14,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    backgroundColor: colors.surfaceMuted,
  },
  pinChipSelected: {
    backgroundColor: colors.primary,
  },
  pinChipText: {
    color: colors.textStrong,
    fontSize: 12,
    fontWeight: "900",
  },
  pinChipTextSelected: {
    color: colors.textOnPrimary,
  },
  loadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
  },
  helper: {
    fontSize: 12,
    color: colors.textStrong,
  },
  suggestionsList: {
    gap: 8,
    paddingVertical: 2,
  },
  suggestionCard: {
    width: 190,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 12,
    backgroundColor: colors.surface,
  },
  suggestionCardSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  suggestionTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.text,
  },
  suggestionSubtitle: {
    marginTop: 3,
    fontSize: 11,
    color: colors.textStrong,
  },
  typeRow: {
    flexDirection: "row",
    gap: 8,
  },
  typeButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    backgroundColor: colors.surface,
  },
  typeButtonSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  typeLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.primary,
  },
  typeLabelSelected: {
    color: colors.textOnPrimary,
  },
  stepperRow: {
    minHeight: 44,
    borderRadius: 16,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.surfaceMuted,
  },
  stepperLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: colors.text,
  },
  stepperControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  stepperButton: {
    width: 32,
    height: 32,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  stepperValue: {
    minWidth: 24,
    textAlign: "center",
    fontSize: 14,
    fontWeight: "900",
    color: colors.text,
  },
  markerActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  markerAction: {
    flexGrow: 1,
    flexBasis: "22%",
    minHeight: 48,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    backgroundColor: colors.surface,
  },
  markerActionActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  markerActionDanger: {
    borderColor: "#FECACA",
    backgroundColor: "#FEF2F2",
  },
  markerActionText: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.primary,
  },
  markerActionDangerText: {
    color: colors.danger,
  },
  createButton: {
    height: 50,
    borderRadius: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: colors.primary,
  },
  createButtonDisabled: {
    opacity: 0.55,
  },
  createText: {
    color: colors.textOnPrimary,
    fontSize: 15,
    fontWeight: "800",
  },

  // ── Assistant de création (mode BATIMENT) ─────────────────────────────
  wizardProgress: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  wizardProgressLabel: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.4,
    textTransform: "uppercase",
    color: colors.textSubtle,
  },
  wizardDot: {
    flex: 1,
    height: 4,
    borderRadius: 3,
    backgroundColor: colors.border,
  },
  wizardDotOn: {
    backgroundColor: colors.primary,
  },
  wizardHint: {
    fontSize: 12,
    color: colors.textMuted,
    textAlign: "center",
  },
  typeCardList: {
    gap: 8,
  },
  typeCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 14,
    padding: 11,
    backgroundColor: colors.surface,
  },
  typeCardSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  typeCardIcon: {
    width: 38,
    height: 38,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceMuted,
  },
  typeCardIconSelected: {
    backgroundColor: colors.surface,
  },
  typeCardName: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.text,
  },
  typeCardDesc: {
    fontSize: 11,
    color: colors.textMuted,
  },
  typeCardRank: {
    marginLeft: "auto",
    fontSize: 10.5,
    fontWeight: "800",
    color: colors.primary,
  },
  optionRow: {
    minHeight: 44,
    borderRadius: 12,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  optionLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.textStrong,
  },
  codeInput: {
    minHeight: 44,
    borderRadius: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    fontSize: 13,
    fontWeight: "600",
    color: colors.text,
  },
  searchField: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minHeight: 44,
    borderRadius: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
    color: colors.text,
    paddingVertical: 0,
  },
  addressList: {
    gap: 8,
    maxHeight: 176,
  },
  addressRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 10,
    backgroundColor: colors.surface,
  },
  addressRowSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  addressCheck: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
  },
  addressTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.text,
  },
  addressSubtitle: {
    marginTop: 2,
    fontSize: 11,
    color: colors.textMuted,
  },
  recapCard: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    padding: 12,
    gap: 7,
    backgroundColor: colors.surfaceMuted,
  },
  recapRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  recapKey: {
    fontSize: 12,
    color: colors.textMuted,
  },
  recapValue: {
    fontSize: 12.5,
    fontWeight: "800",
    color: colors.text,
    flexShrink: 1,
    textAlign: "right",
  },
  recapTotalRow: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    borderStyle: "dashed",
    paddingTop: 8,
    marginTop: 1,
  },
  recapTotalValue: {
    color: colors.primary,
  },
  wizardActions: {
    flexDirection: "row",
    gap: 8,
  },
  wizardBackButton: {
    height: 50,
    paddingHorizontal: 18,
    borderRadius: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderWidth: 1.5,
    borderColor: colors.primaryRing,
    backgroundColor: colors.surface,
  },
  wizardBackText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: "800",
  },
  wizardPrimary: {
    flex: 1,
  },
});
